### ISSUE TITLE
Receive message using "qname" rather than ":qname"

### ISSUE THREAD

**Issue by YJChan** [Couragium/rsmq-async-rs#13]
Hi, 
I've follow to example, ```let message = rsmq.receive_message::<String>("myqueue", None).await?;``` but I always get queue not found error. So, I try using ```let message = rsmq.receive_message::<String>(":myqueue", None).await?;```. Can I confirm that this is a mistake?

**Comment by DavidBM** [comment]
It seems that the JS library add the `:` to the queue name and this one doesn't. Let me check the JS source code and see. I will update the library if there is any mismatch.

**Comment by DavidBM** [comment]
I cannot see where are the `:` comming from. What library created the queue initially in the Redis instance?

As you can see in the tests, https://github.com/Couragium/rsmq-async-rs/blob/master/tests/test.rs#L18 it should work without prepending anything.

**Comment by YJChan** [comment]
Wasn't check on my notification recently. There is ```:``` in my redis queue created by other node.js service by accident. I will proceed to close this issue. Thank you for verifying it.
